<ul class="list-group list-group-flush mt-5">
    <li class="list-group-item">Nama Lengkap: {{ auth()->user()->nama }}</li>
    <li class="list-group-item">NIK: {{ auth()->user()->nik }}</li>
    <li class="list-group-item">Email: {{ auth()->user()->email }}</li>
    <li class="list-group-item">Nama Usaha: {{ auth()->user()->nama_usaha }}</li>
    <li class="list-group-item">Telpon: {{ auth()->user()->no_telp }}</li>
    <li class="list-group-item">NPWP: {{ auth()->user()->npwp }}</li>
    <li class="list-group-item">No IUMK: {{ auth()->user()->no_iumk }}</li>
    <li class="list-group-item">No SIUP: {{ auth()->user()->no_siup }}</li>
    <li class="list-group-item">No TDP: {{ auth()->user()->no_tdp }}</li>
    <li class="list-group-item">Tanggal Mulai: {{ auth()->user()->tgl_mulai }}</li>
    <li class="list-group-item">Sektor Usaha: {{ auth()->user()->sektor_usaha }}</li>
    <li class="list-group-item">Sentra: {{ auth()->user()->sentra }}</li>
    <li class="list-group-item">Alamat: {{ auth()->user()->alamat }}</li>
    <li class="list-group-item">Usaha Utama: {{ auth()->user()->usaha_utama }}</li>
    <li class="list-group-item">Produk Hasil: {{ auth()->user()->produk_hasil }}</li>
    <li class="list-group-item">Tenaga Tetap: {{ auth()->user()->tenaga_tetap }}</li>
    <li class="list-group-item">Tenaga Tidak Tetap: {{ auth()->user()->tenaga_tidak_tetap }}</li>
    <li class="list-group-item">Tenaga Tidak Dibayar: {{ auth()->user()->tenaga_tidak_dibayar }}</li>
    <li class="list-group-item">Kapasitas Produksi: {{ auth()->user()->kapasitas_produksi }}</li>
    <li class="list-group-item">Harga Satuan: Rp. {{number_format(auth()->user()->harga_satuan) }}</li>
    <li class="list-group-item">Omzet: Rp. {{number_format(auth()->user()->omzet) }}</li>
    <li class="list-group-item">Modal Sendiri: Rp. {{number_format(auth()->user()->modal_sendiri) }}</li>
    <li class="list-group-item">Modal Luar: Rp. {{number_format(auth()->user()->modal_luar) }}</li>
    <li class="list-group-item">Laporan Keuangan: {{ auth()->user()->laporan_keuangan }}</li>
    <li class="list-group-item">Jangkauan Pemasaran: {{ auth()->user()->jangkauan_pemasaran }}</li>
    <li class="list-group-item">Pemasaran Online: {{ auth()->user()->pemasaran_online }}</li>
</ul>
